# Python Basics

## Containers -- Lists and Arrays

A **list** is a list of quantities of some kind -- integers, floats, strings, ... (not necessarily all the same! but generally is!!!)  
Quantities in a list are called **elements**.

In [1]:
# empty list
my_list = []

# list of integers
my_list = [1, 2, 3]

# list with mixed datatypes
my_list = [1, "Hello", 3.4, 4.5]

# access list through index, the index starts with 0
print("list index 2 =",my_list[2])

# the index can be negative
print("list index -1 = ",my_list[-1])

list index 2 = 3.4
list index -1 =  4.5


In [2]:
# List are mutable
array=[1,3,2,5,5]

# change the forth element
array[3]=4

print(array)

[1, 3, 2, 4, 5]


In [3]:
# add element at the end
array.append(6)
print(array)

# delete element at index
del array[0]
print (array)

# delete element from the end
array.pop()   # add an index inside the brackets to remove from specific position
print (array)

[1, 3, 2, 4, 5, 6]
[3, 2, 4, 5, 6]
[3, 2, 4, 5]


In [4]:
#Fancy way to create a list: List Comprehension
pow2 = [2 ** x for x in range(10)]
print(pow2)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]


In [5]:
# membership operators: in, not in
a=[1,2,3,4]
print(1 in a)
print(1 not in a)

True
False


Arrays are also an ordered set of values, like lists. They differ from lists as follows:
* Number of elements in an array is **fixed**. Cannot add or remove elements once created.
* Elements **must** be of same type.

Arrays have certain advantages over lists:
* Can be two-dimensional or n-dimensional, like matrices or tensors.
* Can perform arithmetic operations on them, like vectors or matrices.
* Are faster!

Arrays can be created using the **numpy** package.

In [6]:
import numpy as np      # using a short nickname for the package

# array of 4 zeros and floating-point data type
a = np.zeros(4,float)   
print(a)

# 2D array of 3x4 size populated with zeros
a = np.zeros([3,4],float)   
print(a)

# empty array
a = np.empty(4,float)   
print(a)

# create a 3D array of 2x2x2 size populated with ones (use the function ones())
a = np.ones([2,2,2],float)
print(a)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0.]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [7]:
# converting list to array
r = [1.0, 1.5, -2.2]
a = np.array(r,float)
print(r,a)
print(type(r),type(a))

[1.0, 1.5, -2.2] [ 1.   1.5 -2.2]
<class 'list'> <class 'numpy.ndarray'>


### Reading array from file -- loadtxt

* Create a text file with the following data:  
    1.0  
    1.5  
    -2.2  
    2.6  
* Save the file as "values.txt", in the same directory as this code.
* Run the following code.

In [8]:
a = np.loadtxt("values.txt",float)
print(a)

[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [5. 6. 7. 8.]]


Repeat this with the data in "values.txt" updated to the following:  
1 2 3 4  
3 4 5 6  
5 6 7 8

## Arithmetic with Arrays

In [9]:
# addition
a = np.array([1,2,3,4])
b = np.array([2,4,6,8])
print(a+b)

[ 3  6  9 12]


In [10]:
# scalar multiplication
c = 2*a
print(c)

[2 4 6 8]


In [11]:
# element by element multiplication, not vector product!!
print(a*b)

[ 2  8 18 32]


### Matrix multiplication
Consider the matrices:
$$ 
\boldsymbol{a} = 
\begin{bmatrix}
1 & 2 & 3 & 4
\end{bmatrix}, \quad \boldsymbol{b} = \begin{bmatrix}
2 \\
4 \\
6 \\
8
\end{bmatrix}
$$
Its matrix multiplication is calculated as:
$$\begin{align*}
\boldsymbol{a}\boldsymbol{b} =& \begin{bmatrix}
1 & 2 & 3 & 4
\end{bmatrix}
\begin{bmatrix}
2 \\
4 \\
6 \\
8
\end{bmatrix}\\
=& \begin{bmatrix}
1\times2+2\times4+3\times6+4\times8
\end{bmatrix}\\
=& \begin{bmatrix}
60
\end{bmatrix}
\end{align*}
$$

In [12]:
# matrix multiplication
print(np.dot(a,b))

60


Compute the following matrix multiplication by hand first:
$$
\begin{pmatrix}
1 & 3\\
2 & 4
\end{pmatrix}
\begin{pmatrix}
4 & -2 \\
-3 & 1
\end{pmatrix}
$$

$$
\begin{pmatrix}
1 & 3\\
2 & 4
\end{pmatrix}
\begin{pmatrix}
4 & -2 \\
-3 & 1
\end{pmatrix} = 
\begin{pmatrix}
1\times4+3\times(-3) & 1\times(-2)+3\times1\\
2\times4 + 4\times(-3) & 2\times(-2)+4\times1
\end{pmatrix} = 
\begin{pmatrix}
-5 & 1 \\
-4 & 0
\end{pmatrix}
$$

In [13]:
# code the matrix multiplication here
a = np.array([[1,3],[2,4]])
b = np.array([[4,-2],[-3,1]])

arow, acol = len(a), len(a[0])
brow, bcol = len(b), len(b[0])

if acol!=brow:
    print("Error! Matrix multiplication not possible! Check the dimensions of a and b.")
else:
    c = np.zeros([arow,bcol])
    for i in range(arow):
        for j in range(bcol):
            for k in range(acol):
                c[i][j] += a[i][k]*b[k][j]
    print("Matrix multiplication of a and b is:")
    print(c)
    print("From numpy.dot():")
    print(np.dot(a,b))

Matrix multiplication of a and b is:
[[-5.  1.]
 [-4.  0.]]
From numpy.dot():
[[-5  1]
 [-4  0]]


### Other handy functions

In [14]:
import numpy as np

# length of an array (1D)
a = np.array([1,2,3,4])
print(len(a))

4


In [15]:
# size and shape of higher dimensional arrays
a = np.array([[1,2,3],[4,5,6]])
print(a.size)
print(a.shape)

6
(2, 3)


Use data extracted from "values.txt" above and calculate the mean of the data. Do this calculation explicitly first. Then compare with the `mean()` function.

In [16]:
# calculate mean explicitly
a = np.loadtxt("values.txt")
print("Values in data file:")
print(a)
row, col = len(a), len(a[0])
s = 0
for i in range(row):
    for j in range(col):
        s += a[i][j]
print("Mean of elements in a:",s/row/col)

Values in data file:
[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [5. 6. 7. 8.]]
Mean of elements in a: 4.5


In [17]:
# use mean() to calculate mean
print("Mean calculated by numpy.mean():",np.mean(a))

Mean calculated by numpy.mean(): 4.5


Now run the following code and try to understand the output it produces (check out this website: <https://www.stat.berkeley.edu/~spector/extension/python/notes/node53.html>).

In [18]:
a = np.array([1,1])
b = a   # variable b holds the address to variable a
a [0] = 2    # any change in a is thus, reflected in b
print(a)
print(b)

[2 1]
[2 1]


In [19]:
a = np.array([1,1])
b = np.copy(a)      
#b = np.array([i for i in a])    # another way of creating a copy
a [0] = 2
print(a)
print(b)

[2 1]
[1 1]


## Slicing

Works with both lists and arrays. Let us say we have a list `r`. Then `r[m:n]` is a subset of `r`, starting with element `m` and going up to **`n-1`th element**.

In [20]:
a = np.array([2,4,6,8,10,12,14,16])
# elements with index 2 to 4
print(a[2:5])

[ 6  8 10]


In [21]:
# or you can select several elements in the list using colon
print("list index 2 to the end = ",a[2:])   # same as a[2:len(a)]
print("list index 0 to 2 = ",a[:3])         # same as a[0:3]

list index 2 to the end =  [ 6  8 10 12 14 16]
list index 0 to 2 =  [2 4 6]


In [22]:
# all elements
print(a[:])

[ 2  4  6  8 10 12 14 16]


## For loops

In [23]:
r = [1, 3, 5]
for n in r:
    print("Square of",n,"is",n**2)
print("Finished")

Square of 1 is 1
Square of 3 is 9
Square of 5 is 25
Finished


In [24]:
for n in range(1,6,2):
    print("Square of",n,"is",n**2)
print("Finished")

Square of 1 is 1
Square of 3 is 9
Square of 5 is 25
Finished


## User-defined function

In [25]:
# write a summation function of your own
def summation(arr):    # function definition: def keyword defines the function, summation is the function name
    val = 0
    for a in arr:
        val += a
    return val         # returning the final result

arr = np.array([1,2,3,4])
s   = summation(arr)   # function call
print(s)

10


### Recursion -- function calling itself
The factorial of a number is defined as
$$ n! = 1\times 2 \times 3 \times ... n $$
This can also be written as
$$ n! = n(n-1)!$$
with the special cases: $1!=1$ and $0!=1$. Thus, we can write this as
$$n!=\begin{cases}
1 & {\rm if}\ n=0\ {\rm or}\ n=1 \\
n(n-1)! & {\rm if}\ n>1
\end{cases}$$

In [26]:
# recursion to calculate factorial
def factorial(n):
    if n==0 or n==1:
        return 1
    else:
        return n*factorial(n-1)
N = 4
print(factorial(N))

24


### Good programming practices

* Include comments
* Use meaningful variable names
* Functions/modules are always imported at the beginning
* Give names to constants and assign them in the beginning
* Print out partial results and updates throughout the program
* Lay out programs clearly: use space appropriately; long expressions can be broken down into multiple lines using '\'
* Keep it simple!

# Try it yourself

### Total 4 marks (2 marks each)

1. Suppose arrays a and b are defined as follows:  
`from numpy import array`  
`a = array([1,2,3,4])`  
`b = array([2,4,6,8])`  
   What will the computer print upon executing the following:  
        i. `print(b/a+1)`  
        ii. `print(b/(a+1))`  
        iii. `print(1/a)`  
    First calculate these by hand and show your work. Then write a code to print the results and compare.

i. $ \frac{b}{a} + 1 = \frac{[2,4,6,8]}{[1,2,3,4]}+1 = [2,2,2,2] + 1 = [3,3,3,3] $  
ii. $ \frac{b}{a+1} = \frac{[2,4,6,8]}{[1,2,3,4]+1} = \frac{[2,4,6,8]}{[2,3,4,5]} = [1,1.33,2,1.6]$  
iii. $ \frac{1}{a} = \frac{1}{[1,2,3,4]} = [1,0.5,0.33,0.25] $

In [27]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([2,4,6,8])

print("b/a+1:",b/a+1)
print("b/(a+1):",b/(a+1))
print("1/a:",1/a)

b/a+1: [3. 3. 3. 3.]
b/(a+1): [1.         1.33333333 1.5        1.6       ]
1/a: [1.         0.5        0.33333333 0.25      ]


2. Calculate the sum of first N natural numbers using a for loop. Ask user to enter a value for N. Verify this result using the standard formula:  
$$ S_N = \frac{N(N+1)}{2}$$    

In [28]:
N = int(input("Enter N for the sum of first N natural numbers: "))
s = 0
for i in range(1,N+1):
    s += i
print("The sum of first",N,"natural numbers is",s)
print("This matches with the formula for the sum of first N natural numbers, N(N+1)/2:",N*(N+1)/2)

Enter N for the sum of first N natural numbers: 10
The sum of first 10 natural numbers is 55
This matches with the formula for the sum of first N natural numbers, N(N+1)/2: 55.0
